import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import NavBar from "@/components/layout/NavBar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const locale = (await params).locale || "en";
  let messages;
  try {
    messages = (await import(`@/messages/${locale}.json`)).default;
  } catch (error) {
    console.error(`Failed to load messages for locale ${locale}`, error);
    messages = (await import(`@/messages/en.json`)).default;
  }

  return (
    <NextIntlClientProvider messages={messages} locale={locale}>
      <main className="flex flex-col w-screen ">
        <NavBar />
        {children}
      </main>
    </NextIntlClientProvider>
  );
}
